### ISSUE TITLE
uppercase switch

### ISSUE THREAD

**Issue by alwinkpc** [future-architect/Sublime-uroboroSQL-formatter#4]
Greetings, First of all, nice package.

The package option `uf_uppercase` (boolean) changes reserved words and tables/columns indifferently. In `MySQL` without `lower_case_table_names` set to 1 this breaks queries. Can you please be more open allowing:

* `uf_all_uppercase` actual behavior
* `uf_reserved_case` for reserved words
* `uf_tables_case` for tables
* `uf_columns_case` for columns
* `uf_reserved_words` with a list of words to be considered in `uf_reserved_case`

**Comment by FutureArchitect-ichikawa2281** [comment]
Hi @alwinkpc 
I updated the code to allow users to be able to set "uf_case", "uf_reserved_case" and "uf_reserved_words" indifferently. Please update the plugin to accommodate the new version!
